run-search-tests:
	@mocha src/testing/search.test.js

run-sign-in-tests:
	@mocha src/testing/test_sign_in.js

run-sign-up-tests:
	@mocha src/testing/test_sign_up.js

run-cart-ui-tests:
	@mocha src/testing/test_cart_and_purchase.js

run-profile-ui-tests:
	@mocha src/testing/test_profile.js
